// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjxWlIBFeIQVYKvvuxLBHvcCnPUP45GaQ',
    appId: '1:480086335740:web:13fe107e47e74935db3779',
    messagingSenderId: '480086335740',
    projectId: 'rally-fotografico-6c7e7',
    authDomain: 'rally-fotografico-6c7e7.firebaseapp.com',
    storageBucket: 'rally-fotografico-6c7e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmm5x9ZVcRIgsypPJp7jZ1dd-7wIvzeLw',
    appId: '1:480086335740:android:ab60d5a4e2eed949db3779',
    messagingSenderId: '480086335740',
    projectId: 'rally-fotografico-6c7e7',
    storageBucket: 'rally-fotografico-6c7e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfHGEx7FxG9d0oKbktxJk2ODceNfOUy_A',
    appId: '1:480086335740:ios:bffed824c82f10d0db3779',
    messagingSenderId: '480086335740',
    projectId: 'rally-fotografico-6c7e7',
    storageBucket: 'rally-fotografico-6c7e7.firebasestorage.app',
    iosBundleId: 'com.example.rallyFotografico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfHGEx7FxG9d0oKbktxJk2ODceNfOUy_A',
    appId: '1:480086335740:ios:bffed824c82f10d0db3779',
    messagingSenderId: '480086335740',
    projectId: 'rally-fotografico-6c7e7',
    storageBucket: 'rally-fotografico-6c7e7.firebasestorage.app',
    iosBundleId: 'com.example.rallyFotografico',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjxWlIBFeIQVYKvvuxLBHvcCnPUP45GaQ',
    appId: '1:480086335740:web:d67642b16bacfc1edb3779',
    messagingSenderId: '480086335740',
    projectId: 'rally-fotografico-6c7e7',
    authDomain: 'rally-fotografico-6c7e7.firebaseapp.com',
    storageBucket: 'rally-fotografico-6c7e7.firebasestorage.app',
  );
}
